# Generated by Django 5.0.3 on 2024-04-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricecalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_pincode1', models.CharField(max_length=100)),
                ('pickup_address1', models.CharField(max_length=100)),
                ('dropoff_pincode2', models.CharField(max_length=100)),
                ('dropoff_address2', models.CharField(max_length=100)),
                ('distance', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
