# Generated by Django 5.0.3 on 2024-04-21 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pricecalculation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('J', 'Jammu and Kashmir'), ('L', 'Ladakh'), ('H', 'Himachal Pradesh'), ('P', 'Punjab'), ('CH', 'Chandigarh'), ('H', 'Haryana'), ('N', 'NCT of Delhi'), ('U', 'Uttarakhand'), ('U', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('B', 'Bihar'), ('O', 'Odisha'), ('JH', 'Jharkhand'), ('SK', 'Sikkim'), ('A', 'Arunachal Pradesh'), ('AS', 'Assam'), ('M', 'Manipur'), ('MG', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('T', 'Tripura'), ('MP', 'Madhya Pradesh'), ('CG', 'Chhattisgarh'), ('RJ', 'Rajasthan'), ('GJ', 'Gujarat'), ('MH', 'Maharashtra'), ('GA', 'Goa'), ('KA', 'Karnataka'), ('AP', 'Andhra Pradesh'), ('TS', 'Telangana'), ('TN', 'Tamil Nadu'), ('KL', 'Kerala'), ('PY', 'Puducherry'), ('AN', 'Andaman and Nicobar Islands'), ('LD', 'Lakshadweep'), ('DN', 'Dadra and Nagar Haveli and Daman and Diu')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
