# Generated by Django 5.0.3 on 2024-05-20 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merchantmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('pickupAddress', models.CharField(max_length=200)),
                ('pickupPincode', models.CharField(max_length=20)),
                ('pickupMobile', models.CharField(max_length=20)),
                ('deliveryAddress', models.CharField(max_length=200)),
                ('deliveryPincode', models.CharField(max_length=6)),
                ('deliveryMobile', models.CharField(max_length=20)),
                ('sendingType', models.CharField(max_length=100)),
                ('secureParcel', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentType', models.CharField(max_length=100)),
                ('delivery_price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('weight1', models.FloatField()),
                ('pickupAddress1', models.CharField(max_length=200)),
                ('pickupPincode1', models.CharField(max_length=20)),
                ('pickupMobile1', models.CharField(max_length=20)),
                ('deliveryAddress1', models.CharField(max_length=200)),
                ('deliveryPincode1', models.CharField(max_length=6)),
                ('deliveryMobile1', models.CharField(max_length=20)),
                ('departDate', models.DateTimeField()),
                ('arriveDate', models.DateTimeField()),
                ('sendingType1', models.CharField(max_length=100)),
                ('secureParcel1', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentType1', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
