# Generated by Django 5.0.3 on 2024-05-28 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_service1_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service1',
            name='date_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
