# Generated by Django 5.0.3 on 2024-05-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_service1_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='service1',
            name='order_id',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
