# Generated by Django 5.0.3 on 2024-05-28 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_service1_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service2',
            name='date_ordered1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service2',
            name='delivery_price1',
            field=models.IntegerField(default=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service2',
            name='order_id1',
            field=models.IntegerField(default=1222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service2',
            name='order_status1',
            field=models.CharField(blank=True, choices=[('Processing', 'processing'), ('On-Hold', 'On-Hold'), ('Cancel', 'Cancel'), ('Picked Up', 'Picked up'), ('Completed', 'Completed')], max_length=50, null=True),
        ),
    ]
