# Generated by Django 5.0.3 on 2024-05-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_service2_date_ordered1_service2_delivery_price1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service1',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Processing', 'processing'), ('On-Hold', 'On-Hold'), ('Cancel', 'Cancel'), ('Picked Up', 'Picked up'), ('Completed', 'Completed')], default='processing', max_length=50, null=True),
        ),
    ]
