# Generated by Django 5.0.3 on 2024-05-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_service1_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.IntegerField(default=7044021273),
            preserve_default=False,
        ),
    ]
