# Generated by Django 5.0.3 on 2024-05-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_contactmessage_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantmessage',
            old_name='contact_designation',
            new_name='merchant_designation',
        ),
        migrations.AddField(
            model_name='merchantmessage',
            name='contact_no',
            field=models.IntegerField(default=7044021273),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchantmessage',
            name='business_category',
            field=models.CharField(choices=[('Apparels, Lifestyle', 'Retail'), ('Food, Meals, Catering', 'Service'), ('Cake, Bakery, Dairy, Sweets, Chocolate', 'Retail'), ('Frozen foods, Icecream, Desserts', 'Retail'), ('Gadgets & Electronics', 'Retail'), ('Gifts & Toys', 'Retail'), ('Florist', 'Retail'), ('Groceries', 'Retail'), ('Meat, Fish, Egg', 'Retail'), ('Fresh F & V', 'Retail'), ('Handicrafts, Artisans', 'Retail'), ('Pharma & Medical', 'Retail'), ('Health & Wellness', 'Service'), ('E-commerce', 'Service'), ('Home Decor', 'Retail'), ('Pet', 'Retail'), ('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('Manufacturing', 'Manufacturing'), ('Service', 'Service'), ('Other', 'Other')], max_length=100),
        ),
    ]
