# Generated by Django 5.0.3 on 2024-05-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_merchantmessage_business_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantmessage',
            name='mobile_no',
        ),
    ]
